"use client";

import { useState } from "react";
import type { Trip } from "@/types/itinerary";

interface Props {
  trip: Trip;
  onClose: () => void;
}

function buildSummary(trip: Trip): string {
  const lines: string[] = [
    `${trip.destination} — ${trip.duration_days}-Day Itinerary`,
    `Budget: ${trip.practical_info.budget_estimate}`,
    "",
  ];

  for (const day of trip.days) {
    lines.push(
      `Day ${day.day}${day.region ? ` · ${day.region}` : ""}: ${day.theme}`,
      `Date: ${day.date}`,
      `Morning: ${day.morning}`,
      `Afternoon: ${day.afternoon}`,
      `Evening: ${day.evening}`
    );

    if (day.food?.length) {
      day.food.forEach((f) =>
        lines.push(`${f.must_try ? "★ " : ""}${f.name}: ${f.note}`)
      );
    }

    if (day.stay) {
      lines.push(`Stay: ${day.stay.name} (${day.stay.price})`);
    }

    const total = day.costs?.find((c) =>
      c.item.toLowerCase().includes("total")
    );
    if (total) lines.push(`Daily total: ${total.cost}`);

    if (day.tips) lines.push(`Tip: ${day.tips}`);

    lines.push("");
  }

  lines.push(
    "─ Practical Info ─",
    `Best time to visit: ${trip.practical_info.best_time_to_visit}`,
    `Currency: ${trip.practical_info.currency}`,
    `Transport: ${trip.practical_info.transport_tips}`,
    "",
    "AI-generated by Roamly (roamly.vercel.app). Verify prices and hours before booking."
  );

  return lines.join("\n");
}

type Status = "idle" | "sending" | "sent" | "error";

export default function EmailModal({ trip, onClose }: Props) {
  const [email, setEmail] = useState("");
  const [status, setStatus] = useState<Status>("idle");
  const [errorMsg, setErrorMsg] = useState("");

  const handleSend = async () => {
    if (!email.trim()) return;
    setStatus("sending");
    setErrorMsg("");

    const summary = buildSummary(trip);

    try {
      const res = await fetch("/api/email", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          to: email.trim(),
          destination: trip.destination,
          duration: trip.duration_days,
          budgetEstimate: trip.practical_info.budget_estimate,
          summary,
        }),
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error ?? "Failed to send");
      }

      if (data.sent) {
        setStatus("sent");
      } else if (data.mailto) {
        // Fallback: open mail client
        const mailtoUrl = `mailto:${encodeURIComponent(email.trim())}?subject=${data.subject}&body=${data.body}`;
        window.open(mailtoUrl);
        setStatus("sent");
      }
    } catch (err) {
      setErrorMsg(err instanceof Error ? err.message : "Something went wrong");
      setStatus("error");
    }
  };

  return (
    <div className="fixed inset-0 z-[9999] bg-[var(--overlay)] backdrop-blur-md flex items-center justify-center p-4">
      <div className="bg-white rounded-3xl shadow-2xl border border-[var(--sand)] w-full max-w-sm animate-scale-in">
        <div className="px-6 pt-6 pb-2 flex items-center justify-between">
          <h2 className="font-[family-name:var(--font-playfair)] text-lg font-bold text-[var(--ink)]">
            Email Itinerary
          </h2>
          <button
            onClick={onClose}
            className="text-[var(--muted)] hover:text-[var(--ink)] text-xl"
          >
            &times;
          </button>
        </div>

        <div className="px-6 py-4">
          {status === "sent" ? (
            <div className="text-center py-6">
              <div className="w-12 h-12 rounded-full bg-[var(--sage)]/10 flex items-center justify-center mx-auto mb-3">
                <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="var(--sage)" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                  <polyline points="20 6 9 17 4 12" />
                </svg>
              </div>
              <p className="font-medium text-[var(--ink)]">Itinerary sent!</p>
              <p className="text-sm text-[var(--muted)] mt-1">
                Check your inbox at {email}
              </p>
              <button
                onClick={onClose}
                className="mt-5 px-6 py-2.5 rounded-xl bg-[var(--ink)] text-[var(--paper)] text-sm font-medium hover:bg-[var(--rust)] transition"
              >
                Done
              </button>
            </div>
          ) : (
            <>
              <p className="text-sm text-[var(--muted)] mb-4">
                Send the full {trip.destination} itinerary to your email.
              </p>
              <input
                type="email"
                autoFocus
                placeholder="your@email.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleSend()}
                className="w-full px-4 py-3 rounded-xl border border-[var(--sand)] bg-[var(--paper)] text-[var(--ink)] placeholder:text-[var(--muted)]/50 focus:outline-none focus:border-[var(--amber)] focus:ring-2 focus:ring-[var(--amber)]/15 transition text-sm"
              />
              {status === "error" && (
                <p className="text-xs text-[var(--rust)] mt-2">{errorMsg}</p>
              )}
              <button
                onClick={handleSend}
                disabled={status === "sending" || !email.trim()}
                className="mt-3 w-full py-3 rounded-xl bg-[var(--ink)] text-[var(--paper)] text-sm font-medium hover:bg-[var(--rust)] transition disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                {status === "sending" ? (
                  <>
                    <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24" fill="none">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                    </svg>
                    Sending...
                  </>
                ) : (
                  <>
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z" /><polyline points="22,6 12,13 2,6" />
                    </svg>
                    Send Itinerary
                  </>
                )}
              </button>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
